### ISSUE TITLE
ddm.plot.plot_decision_variable_distribution() missing?

### ISSUE THREAD

**Issue by stefan-f-bucher** [mwshinn/PyDDM#6]
In version 0.1.3 I'm getting an Attribute error ('module 'ddm.plot' has no attribute 'plot_decision_variable_distribution') when calling ddm.plot.plot_decision_variable_distribution() - has it been removed from PyDDM?

**Comment by mwshinn** [comment]
I can't reproduce this error on 0.2.0.  Could you please provide a minimal example which demonstrates this error?

**Comment by stefan-f-bucher** [comment]
After updating to 0.2.0 the error does not reproduce.
